# Generated by Django 4.2 on 2023-06-01 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_id_bids_bid_id_rename_id_comments_comment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='listing',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='listing',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='starting_price',
            new_name='current_price',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='user',
            new_name='user_id',
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_watchlist', to='auctions.listings')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_watching', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
