# Generated by Django 4.2 on 2023-06-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_listing_bids_listing_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='img',
            field=models.TextField(blank=True),
        ),
    ]
