# Generated by Django 4.2 on 2023-06-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listings_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, choices=[('fashion', 'fashion'), ('toys', 'toys'), ('electronics', 'electronics'), ('home', 'home')], default='fashion', max_length=20),
        ),
    ]
