# Generated by Django 4.2 on 2023-06-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_posts_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
